my_hugs.settings:
  type: mapping
  label: 'My-Hug Module Settings'
  mapping:
    default_count:
      type: integer
      label: 'Defaultttt my_hug count'
    exp_string:
      type: string
      label: 'Experimental string defined in config/schema/...'
