my_hugs.settings:
  type: mapping
  label: 'My-Hug Module Settings'
  mapping:
    default_count:
      type: integer
      label: 'Defaultttt my_hug count'
    exp_string:
      type: string
      label: 'Experimental string defined in config/schema/...'
    exp_text:
      type: text
      label: 'Experimental text input field defined in config/schema/...'
    idmg_phone_nav_on_phones:
      type: radios
      label: 'Select whether the jQuery Header and yadda yadda...'
